services:
  nginx:
    image: nginx:latest
    ports:
      - "3100:3100" # Might want to change this port later.

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - core
      - auth
      - database
      - function
    networks:
      - envy

  core:
    networks:
      - envy
    image: ghcr.io/orbical-dev/envybase-core:stable
    build: apps/core
    expose:
      - "3000"
    environment:
      - DOCKER=False

  auth:
    depends_on:
      - mongodb
    image: ghcr.io/orbical-dev/envybase-auth:stable
    build: apps/auth
    networks:
      - envy
    expose:
      - "3121"
    environment:
      - DOCKER=False
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PASSWORD_MIN_LENGTH=8
      - PASSWORD_MAX_LENGTH=32
      - USERNAME_MIN_LENGTH=3
      - USERNAME_MAX_LENGTH=32
      - ISSUER=your_issuer
      - AUTH_KEY=your_auth_key
      - ISSECURE=False
      - ISCLOUDFLARE=False

  database:
    networks:
      - envy
    depends_on:
      - mongodb
    image: ghcr.io/orbical-dev/envybase-database:stable
    build: apps/database
    expose:
      - "3122"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - ISCLOUDFLARE=False
      - DOCKER=False

  func:
    networks:
      - envy
    depends_on:
      - mongodb
    image: ghcr.io/orbical-dev/envybase-func:stable
    build: apps/function
    expose:
      - "3123"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - ISCLOUDFLARE=False
      - DOCKER=False
  mongodb:
    networks:
      - envy
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  redis:
    networks:
      - envy
    image: redis:latest
    volumes:
      - redis_data:/data

networks:
  envy:

volumes:
  mongodb_data:
  redis_data:
